#!/usr/bin/env node
// Turns a course data file (see src/data/courses/classic-set-essentials.js) into an idempotent SQL
// script for the academy tables from 0005_academy_courses.sql.
//
//   node scripts/course-to-sql.mjs src/data/courses/classic-set-essentials.js > supabase/migrations/0007_course_classic_set_essentials.sql
//
// Row ids are derived from the course slug, so re-running the SQL updates the same rows instead of
// duplicating them. The file must export one course object (the first export that has a `modules` array).

import { createHash } from "node:crypto";
import { pathToFileURL } from "node:url";
import { resolve } from "node:path";

const file = process.argv[2];
if (!file) { console.error("usage: node scripts/course-to-sql.mjs <course-file.js>"); process.exit(1); }

const mod = await import(pathToFileURL(resolve(file)).href);
const c = Object.values(mod).find((v) => v && typeof v === "object" && Array.isArray(v.modules));
if (!c) { console.error("No exported course object with a `modules` array found."); process.exit(1); }

const uuid = (s) => {
  const h = createHash("sha1").update("lashtribe-academy:" + s).digest("hex");
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-5${h.slice(13, 16)}-a${h.slice(17, 20)}-${h.slice(20, 32)}`;
};
const q = (v) => (v == null ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const j = (v) => {
  const t = JSON.stringify(v);
  if (t.includes("$j$")) throw new Error("content contains the sequence $j$");
  return `$j$${t}$j$::jsonb`;
};

const cid = uuid(c.slug);
const counts = c.modules.reduce((n, m) => n + m.lessons.length, 0);
let out = `-- ${c.title} (${c.modules.length} modules, ${counts} lessons)
-- Generated by scripts/course-to-sql.mjs. Safe to re-run: rows are upserted by id.
-- Remove the course:  delete from public.courses where slug = ${q(c.slug)};

insert into public.courses (id, slug, title, subtitle, description, level, is_free, price, sequential, certificate_enabled, bonus_points, status, sort_order)
values (${q(cid)}, ${q(c.slug)}, ${q(c.title)}, ${q(c.subtitle)}, ${q(c.description)}, ${q(c.level || "beginner")}, ${c.is_free !== false}, ${c.price || 0}, ${!!c.sequential}, ${c.certificate_enabled !== false}, ${c.bonus_points || 0}, 'published', ${c.sort_order ?? 10})
on conflict (id) do update set slug = excluded.slug, title = excluded.title, subtitle = excluded.subtitle, description = excluded.description,
  level = excluded.level, is_free = excluded.is_free, price = excluded.price, sequential = excluded.sequential,
  certificate_enabled = excluded.certificate_enabled, bonus_points = excluded.bonus_points, status = 'published';

`;
let order = 0;
c.modules.forEach((m, mi) => {
  const mid = uuid(`${c.slug}:m${mi + 1}`);
  out += `-- Module ${mi + 1}: ${m.title}\ninsert into public.course_modules (id, course_id, title, sort_order) values (${q(mid)}, ${q(cid)}, ${q(m.title)}, ${mi})
on conflict (id) do update set title = excluded.title, sort_order = excluded.sort_order;\n`;
  m.lessons.forEach((l) => {
    order += 1;
    const lid = uuid(`${c.slug}:l${order}`);
    out += `insert into public.lessons (id, course_id, module_id, title, kind, summary, duration_seconds, read_minutes, is_preview, sort_order, status)
values (${q(lid)}, ${q(cid)}, ${q(mid)}, ${q(l.title)}, ${q(l.kind)}, ${q(l.summary)}, ${l.video?.duration || 0}, ${l.read_minutes || 0}, ${!!l.is_preview}, ${order}, 'published')
on conflict (id) do update set module_id = excluded.module_id, title = excluded.title, kind = excluded.kind, summary = excluded.summary,
  duration_seconds = excluded.duration_seconds, read_minutes = excluded.read_minutes, is_preview = excluded.is_preview,
  sort_order = excluded.sort_order, status = 'published';
insert into public.lesson_content (lesson_id, video, blocks) values (${q(lid)}, ${j(l.video || null)}, ${j(l.blocks || [])})
on conflict (lesson_id) do update set video = excluded.video, blocks = excluded.blocks;\n`;
  });
  out += "\n";
});
process.stdout.write(out);
